"use strict";

const rules = {
  "unicorn/better-regex": "error",
  "unicorn/catch-error-name": ["error", {
    "ignore": [
      "^(error)$",
      "^(err)$",
      "^(e)$",
    ],
  }],
  "unicorn/consistent-destructuring": "error",
  "unicorn/consistent-function-scoping": "off",
  "unicorn/custom-error-definition": "error",
  "unicorn/empty-brace-spaces": "warn",
  "unicorn/error-message": "error",
  "unicorn/escape-case": "error",
  "unicorn/expiring-todo-comments": "off", // later
  "unicorn/explicit-length-check": ["error", {
    "non-zero": "greater-than",
  }],
  "unicorn/filename-case": "off",
  "unicorn/import-index": ["error", {
    "ignoreImports": true,
  }],
  "unicorn/import-style": "off",
  "unicorn/new-for-builtins": "error",
  /*     */"no-new-wrappers": "off",
  "unicorn/no-abusive-eslint-disable": "off",
  "unicorn/no-instanceof-array": "error",
  "unicorn/no-console-spaces": "error",
  "unicorn/no-array-callback-reference": "off",
  "unicorn/no-array-for-each": "off",
  "unicorn/no-array-push-push": "error",
  "unicorn/no-for-loop": "error",
  "unicorn/no-hex-escape": "error",
  "unicorn/no-keyword-prefix": "off",
  "unicorn/no-lonely-if": "off", // sonarjs alt, eslint alt*
  "unicorn/no-nested-ternary": "off", // eslint alt
  "unicorn/no-new-array": "warn", // eslint alt*
  "unicorn/no-new-buffer": "error",
  "unicorn/no-null": "off",
  "unicorn/no-object-as-default-parameter": "error",
  "unicorn/no-process-exit": "off",
  "unicorn/no-this-assignment": "warn",
  "unicorn/no-array-reduce": "off",
  "unicorn/no-unreadable-array-destructuring": "error",
  "unicorn/no-unsafe-regex": "error",
  "unicorn/no-unused-properties": "off",
  "unicorn/no-useless-undefined": "off",
  "unicorn/no-zero-fractions": "error",
  "unicorn/number-literal-case": "error",
  "unicorn/numeric-separators-style": ["warn", {
    "number": {
      "minimumDigits": 5,
      "groupLength": 3,
    },
  }],
  "unicorn/prefer-add-event-listener": "off",
  "unicorn/prefer-array-find": "error",
  "unicorn/prefer-array-some": "error",
  "unicorn/prefer-date-now": "warn",
  "unicorn/prefer-default-parameters": "error",
  "unicorn/prefer-dom-node-dataset": "off",
  "unicorn/prefer-keyboard-event-key": "off",
  "unicorn/prefer-array-flat-map": "error", // array-func alt
  "unicorn/prefer-array-index-of": "error",
  "unicorn/prefer-includes": "error",
  "unicorn/prefer-math-trunc": "off",
  "unicorn/prefer-modern-dom-apis": "off",
  "unicorn/prefer-negative-index": "off",
  "unicorn/prefer-dom-node-append": "off",
  "unicorn/prefer-dom-node-remove": "off",
  "unicorn/prefer-dom-node-text-content": "off",
  "unicorn/prefer-number-properties": "error",
  "unicorn/prefer-optional-catch-binding": "error",
  "unicorn/prefer-query-selector": "off",
  "unicorn/prefer-reflect-apply": "error",
  "unicorn/prefer-regexp-test": "error",
  "unicorn/prefer-string-replace-all": "error",
  "unicorn/prefer-set-has": "off",
  "unicorn/prefer-spread": "off",
  "unicorn/prefer-string-starts-ends-with": "error",
  "unicorn/prefer-string-slice": "error",
  "unicorn/prefer-ternary": "warn",
  "unicorn/prefer-dom-node-text-conten": "off",
  "unicorn/prefer-string-trim-start-end": "error",
  "unicorn/prefer-type-error": "off",
  "unicorn/prevent-abbreviations": "off",
  "unicorn/string-content": "off",
  "unicorn/throw-new-error": "error",
};

module.exports = {
  plugins: ["eslint-plugin-unicorn"],
  rules,
};
